HEP-FCC/k4RecCalorimeter

RecCalorimeter/src/components/CreateCaloClustersSlidingWindow.cpp
This prevents to store, in the new event, the clusters from the previous events. Not sure why/if it was working in the previous fccedm implementation...
=> Fix cluster duplicates

RecCalorimeter/src/components/CaloTopoCluster.cpp, RecCalorimeter/src/components/CaloTowerTool.cpp, RecCalorimeter/src/components/CaloTowerTool.h, RecCalorimeter/src/components/ConeSelection.cpp, RecCalorimeter/src/components/CorrectCaloClusters.cpp, RecCalorimeter/src/components/CorrectCaloClusters.h, RecCalorimeter/src/components/CorrectECalBarrelSliWinCluster.cpp, RecCalorimeter/src/components/CreateCaloCells.cpp, RecCalorimeter/src/components/CreateCaloCellsNoise.cpp, RecCalorimeter/src/components/CreateCaloClusters.cpp, RecCalorimeter/src/components/LayeredCaloTowerTool.cpp, RecCalorimeter/src/components/LayeredCaloTowerTool.h, RecCalorimeter/src/components/MassInv.cpp, RecCalorimeter/src/components/SplitClusters.cpp
- Replace some dedicated types with `auto` and rename others (Cluster -> MutableCluster, ConstCluster -> Cluster) to adapt to the new naming scheme introduced in AIDASoft/podio#205.
- The necessary changes in EDM4hep: key4hep/EDM4hep#132 would break this otherwise. Due to the explict use of Mutable* (in attachCells) this now requires a new version of edm4hep.
- Due to the change in the interface of attachClusters this also now requires a new version of k4fwcore.
=> Adapt to new podio generated class names

RecCalorimeter/CMakeLists.txt, RecFCCeeCalorimeter/CMakeLists.txt, RecFCChhCalorimeter/CMakeLists.txt
Gaudi targets have a Gaudi:: namespace since v35, and k4FWCorePlugins does not need to be linked.
=> cmake: fix some link targets

RecCalorimeter/src/components/CaloTopoCluster.cpp, RecCalorimeter/src/components/CaloTopoCluster.h, RecCalorimeter/src/components/CaloTopoClusterInputTool.cpp, RecCalorimeter/src/components/CaloTopoClusterInputTool.h, RecCalorimeter/src/components/CaloTowerTool.cpp, RecCalorimeter/src/components/CaloTowerTool.h, RecCalorimeter/src/components/CreateCaloClustersSlidingWindow.cpp, RecCalorimeter/src/components/LayeredCaloTowerTool.cpp, RecCalorimeter/src/components/LayeredCaloTowerTool.h, RecCalorimeter/src/components/NoiseCaloCellsFromFileTool.cpp, RecCalorimeter/src/components/NoiseCaloCellsFromFileTool.h, RecCalorimeter/src/components/SplitClusters.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.cpp, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.h
This PR should be merged at the same time as the one in k4FWCore.
Lots of small things that when put together allow to gain a lot.
- CaloTopoClusters: use unordered_map instead of map
- CaloTopoClusters: fix compilation warning
- CaloTopoClusterInputTool: optimize use of map: update values instead
of clearing and filling again
- CaloTopoClusterInputTool: remove unused member variable
- CaloTowerTool: update to use the new interface (do not fill map of
links if not needed)
- CaloTowerTool: micro-optimisation, reduce calls to eta and phi.
- CreateCaloClustersSlidingWindow: use new interface of CaloTowerTool to
not fill map of links if attachCells is not used
- NoiseCaloCellsFromFileTool: use Decoder::get(ID, int) instead of string
- NoiseCaloCellsFromFileTool: simplify finding bin in …
=> Changes for speed improvements in clustering jobs

RecCalorimeter/src/components/CaloTowerTool.cpp
fix for running standalone HCal, otherwise, the code always looks for ECal
=> fix for running standalone HCal

RecCalorimeter/src/components/CreateCaloCells.cpp, RecCalorimeter/src/components/NoiseCaloCellsFromFileTool.cpp, RecCalorimeter/src/components/NoiseCaloCellsFromFileTool.h
- Add the possibility to filter cells without adding noise
- Add the possibility to filter cells based on energy absolute value
=> Add cell filtering functionalities

RecCalorimeter/src/components/CreateCaloCells.cpp, RecCalorimeter/src/components/CreateCaloCells.h, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.cpp, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.h
https://github.com/key4hep/k4FWCore/pull/100 makes the default DataSvc use the Frame, and some of the interfaces for accessing meta data (e.g. cellID strings) will change. This PR changes the access / writing of the cell ID encoding strings to use the new `MetaDataHandle` interface.
=> Use new MetaDataHandles to be compliant with Frame based I/O

RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.cpp, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.h, RecFCCeeCalorimeter/tests/options/reproduceSegfault.py, RecFCCeeCalorimeter/tests/options/runCaloSim.py
Removes unnecessary dependency on system ID.
=> Removing specialized handles for positions tool

RecCalorimeter/src/components/CaloTowerTool.cpp, RecCalorimeter/src/components/CaloTowerTool.h, RecCalorimeter/src/components/CreateCaloClustersSlidingWindow.cpp, RecCalorimeter/src/components/LayeredCaloTowerTool.cpp, RecCalorimeter/src/components/LayeredCaloTowerTool.h, RecCalorimeter/src/components/MassInv.cpp, RecCalorimeter/src/components/PreparePileup.cpp
Needs also changes in the `ITowerTool` from k4FWCore.
=> Removing `struct tower` from the tower tool

RecCalorimeter/src/components/ConstNoiseTool.cpp, RecFCCeeCalorimeter/src/components/CellPositionsECalBarrelPhiThetaSegTool.cpp, RecFCCeeCalorimeter/src/components/CellPositionsECalBarrelPhiThetaSegTool.h, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNeighbours.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNeighbours.h, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNoiseLevelMap.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNoiseLevelMap.h
This PR adds code to create noise map and cell neighbour map for ECAL + HCAL barrel including links between ECAL outermost and HCAL innermost layers.
The code is developed mainly for the inclined cell readout of the Allegro ECAL but also work for an ECAL with more standard phi-theta readout, for which a corresponding cell positioning tool is also implemented in this PR.
=> Combined ECAL+HCAL topoclustering

RecCalorimeter/src/components/CaloTopoClusterInputTool.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h
The `m_allCells` unordered map is to my mind unnecessary as it does not provide any boost in performance, and introduces compulsory zeroing of the map before every event.
Little benchmark on 100 evt:
```
Runtime:
before [s]: 8.456, 8.603, 8.489, 8.452, 8.661
after [s]: 8.492, 8.578, 8.548, 8.398, 8.568
average before[s]: 8.5322
average after[s]: 8.5168
```
Also, fixing issue/crash when running over `ddsim` generated sample(s).
=> Removing m_allCells from CaloTopoClusterFCCee algorithm members

RecCalorimeter/src/components/LayeredCaloTowerTool.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp
In EDM4hep calohit position is float, but `dd4hep::Position` is double.
=> Cell position cast to float

RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.cpp
There was a typo in the cluster decorator  in the final normalisation of the layer theta when linear (E) weights are used.
Also, since the shapeParameters related to the energy are not the raw energies but rather energy fractions (energy in layer / cluster energy), I have renamed the metadata energy_ .. to energy_fraction_ ..
=> fix bug in calculation of theta of layer  barycentre 

RecFCCeeCalorimeter/CMakeLists.txt, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloXTalkNeighbours.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloXTalkNeighbours.h, RecFCCeeCalorimeter/tests/options/runCaloXTalkNeighbours.py
Added two more files "CreateFCCeeCaloXTalkNeighbours.cpp" and "CreateFCCeeCaloXTalkNeighbours.h" in order to loop over the cells of ALLERGRO ECAL barrel and generate a mapping of crosstalk neighbours.
No change is introduced to the existing part of the software package.
Example:
https://github.com/zwu0922/LAr_scripts/blob/main/FCCSW_ecal/xtalk_neighbours_theta.py
In order to produce the list of crosstalk neighbours and coefficients, run
`fccrun xtalk_neighbours_theta.py`
=> Add crosstalk neighbour class

CMakeLists.txt, RecFCCeeCalorimeter/CMakeLists.txt, RecFCCeeCalorimeter/src/components/CalibrateCaloClusters.cpp
Same as https://github.com/HEP-FCC/FCCAnalyses/pull/373. This PR requires changes to be made backwards compatible.
=> Support building with onnxruntime 17.1

RecCalorimeter/src/components/CreateCaloCells.cpp, RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.cpp, RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.h, RecFCCeeCalorimeter/src/components/CalibrateCaloClusters.cpp, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.cpp
This PR fixes two crashes observed with recent nightlies:
1) a crash if the clusters used in input to AugmentedCaloClusters or CalibrateCaloClusters do not have metadata
2) a crash in CalibrateCaloClusters to the update version of the ONNX runtime used by the software stuck
=> Fixes for two types of crashes in recent nightlies

RecFCCeeCalorimeter/CMakeLists.txt, RecFCCeeCalorimeter/src/components/PhotonIDTool.cpp, RecFCCeeCalorimeter/src/components/PhotonIDTool.h
The code in this PR provides a Gaudi algorithm that 
- reads the list of input features from a JSON file and the trained BDT model from an ONNX file
- for each cluster, reads the input features from the shapeParameters vector (if available), runs the inference, and saves the photon probability as an additional shape parameter of the new output cluster collection
It works with ONNX files created with either XGBoost and LightGBM (tested with both).
Could probably work also with different models based on features (DNN..) 
Uses as inputs the shower shapes calculated in https://github.com/HEP-FCC/k4RecCalorimeter/pull/79
=> Implement an algorithm for photon/pi0 discrimination based on input features and a trained model in ONNX format

RecCalorimeter/src/components/ReadCaloCrosstalkMap.cpp, RecCalorimeter/src/components/ReadCaloCrosstalkMap.h
Tools being always initialized, this PR avoids crashing when cross-talk is not needed. Before, `ReadCaloCrosstalkMap` would always be looking for a `xtalk_neighbours_map_ecalB_thetamodulemerged.root` rootfile.
=> Avoid crashing when cross-talk not wanted

RecCalorimeter/src/components/CorrectECalBarrelSliWinCluster.cpp, RecCalorimeter/src/components/MassInv.cpp, RecCalorimeter/src/components/NoiseCaloCellsFromFileTool.cpp, RecCalorimeter/src/components/ReadCaloCrosstalkMap.cpp, RecCalorimeter/src/components/ReadNoiseFromFileTool.cpp, RecCalorimeter/src/components/TopoCaloNeighbours.cpp, RecCalorimeter/src/components/TopoCaloNoisyCells.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNeighbours.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNoiseLevelMap.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloXTalkNeighbours.cpp, RecFCCeeCalorimeter/src/components/ReadNoiseVsThetaFromFileTool.cpp, RecFCCeeCalorimeter/tests/options/run_thetamodulemerged_SW_benchmarkCorr.py, RecFCChhCalorimeter/src/components/CreateFCChhCaloNeighbours.cpp, RecFCChhCalorimeter/src/components/CreateFCChhCaloNoiseLevelMap.cpp
Using ROOT's TSystem facilities...
=> Check that input root files and output directories exist

RecCalorimeter/src/components/CreateTruthJet.cpp
Use `auto` and `Collection::create` to remove the need for an explicit typename to make key4hep/EDM4hep#341 transparent.
@BrieucF another one that is required to make the EDM4hep PR work transparently.
=> Remove the need for an explicit typename

CMakeLists.txt, RecFCCeeCalorimeter/CMakeLists.txt, RecFCCeeCalorimeter/src/components/CalibrateCaloClusters.cpp, RecFCCeeCalorimeter/src/components/CalibrateCaloClusters.h, RecFCCeeCalorimeter/src/components/OnnxruntimeUtilities.h, RecFCCeeCalorimeter/src/components/PhotonIDTool.cpp, RecFCCeeCalorimeter/src/components/PhotonIDTool.h, cmake/FindONNXRuntime.cmake
This PR ensures that newer versions of onnxruntime are preferred by CMake and also that newer versions of onnxruntime actually compile (see also https://github.com/HEP-FCC/FCCAnalyses/pull/381 for some more details than here). In short this PR 
- Makes `FindONNXRuntime.cmake` create the an `onnxruntime::onnxruntime` target that works similar (enough) to the one from `onnxruntime`, such that we can simplify the cmake configuration to only use that.
- Makes the c++ code work with older versions (< 1.13) and newer versions using some pre-processor checks.
The CI has been working because it found an ONNXRuntime version 1.10, but I could not build this with a newer version of onnxruntime locally.
=> Make sure to properly support newer versions of onnxruntime

RecCalorimeter/tests/options/runEcalBarrel_ReconstructionTopoClusters_crosstalk.py, RecCalorimeter/tests/options/runJetReco.py, RecCalorimeter/tests/options/runTruthJetReco.py, RecFCCeeCalorimeter/tests/options/runCaloSim.py, RecFCCeeCalorimeter/tests/options/run_thetamodulemerged.py, RecFCCeeCalorimeter/tests/options/run_thetamodulemerged_SW_benchmarkCorr.py
Fix tests that are broken after removal of EventCounter
=> remove EventCounter in tests

RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.cpp, RecFCCeeCalorimeter/src/components/CalibrateCaloClusters.cpp, RecFCCeeCalorimeter/src/components/PhotonIDTool.cpp
Pointers were not treated correctly in some cases and led to a crash, see discussion in https://github.com/……HEP-FCC/k4RecCalorimeter/pull/104#discussion_r1735675543
Also, one shape parameter for photon ID was being added to clusters even when the flag for adding photon-id related variables was false.
This PR fixes both things
=> fix crash due to wrong treatment of pointers in ONNX-related code, and remove one photon-ID variable from decorations when not needed

RecFCCeeCalorimeter/src/components/CaloTowerToolFCCee.cpp
Re-enable code (disabled at some point in the past) to cluster hcal endcap cells into SW clusters now that we have digitisers for the hcal endcap
=> enable code to cluster hcal endcap cells into SW clusters

RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03.sh, RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03_digi_reco.py
Implements some style suggestion from the previous PR moving scripts to ddsim+k4run (https://github.com/HEP-FCC/k4RecCalorimeter/pull/109) and fixes a couple of small bugs in those scripts
Also implements an option to run over particle gun samples instead of Pythia Z->qq (the latter is the default, but the former can be useful for some local tests)
=> Fix scripts for automatic tests

RecCalorimeter/src/components/CreateTruthJet.cpp
Switch happened in https://github.com/key4hep/EDM4hep/pull/341 and without this. Things will start failing once https://github.com/key4hep/EDM4hep/pull/373 is merged.
=> Switch from Associations to Links

RecCalorimeter/src/components/CaloTopoCluster.cpp, RecCalorimeter/src/components/CaloTopoCluster.h, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h
The topoclustering algorithm adds a shape parameter to the output cluster collection (https://github.com/HEP-FCC/k4RecCalorimeter/blob/b571f7c49595b4b99f98857ef54014658cb51abc/RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp#L225) but it does not declare it in the metadata information of the clusters. Downstream algorithms such as AugmentClustersFCCee append metadata and shape parameters, and algorithms such as MVA calibration or photon ID look at the metadata to identify the position of the input features. The missing info in the topocluster metadata screws up the latter algorithms, as the real input features to be used are shifted by +1 with respect to what the tools extract from the metadata.
This PR fixes the problem by adding proper metadata info to the topoclusters.
=> fix metadata of topoclusters

RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h
when running with noise ON the number of topoclusters is huge. This can be reduced by increasing the thresholds on S/N for the seed cell but still there are a certain number of low-E clusters (typically below 20 MeV) that one might want to get rid of to keep the output size reasonable.
This code adds a property to the topoclustering code that allows the user to set a minimum energy threshold (by default is zero)
Usage example: https://gitlab.cern.ch/gmarchio/FCC-scripts/-/blob/main/run_ALLEGRO_reco.py?ref_type=heads#L893
=> add option to save only topoclusters with E>E=min

.github/workflows/key4hep-build.yaml, README.md
=> Removing CentOs7 from the test matrix

RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.cpp, RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.h
When calculating RMS width of showers in layers of ECAL when noise is on the RMS can be negative due to negative-energy cells. In that case the code was crashing. This PR will set the width to zero for those cases
=> fix photon ID inputs when noise is on

RecCalorimeter/src/components/CaloTopoCluster.h, RecCalorimeter/src/components/CreatePositionedCaloCells.h, RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.h, RecFCCeeCalorimeter/src/components/CalibrateCaloClusters.h, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h, RecFCCeeCalorimeter/src/components/PhotonIDTool.h
After https://github.com/key4hep/k4FWCore/pull/253, `DataHandle.h` will not include `edm4hep/Constants.h` (it should never have because it wasn't being used at least for the last versions) so now this include will need to happen wherever some label from `edm4hep::labels` is used.
=> Include "edm4hep/Constants.h" where it's needed

RecCalorimeter/src/components/CaloTopoClusterInputTool.cpp, RecCalorimeter/src/components/CaloTowerTool.cpp, RecCalorimeter/src/components/CreateCaloCells.h, RecCalorimeter/src/components/CreateCaloCellsNoise.h, RecCalorimeter/src/components/CreateCaloClusters.cpp, RecCalorimeter/src/components/CreateCaloClusters.h, RecCalorimeter/src/components/LayeredCaloTowerTool.cpp, RecCalorimeter/src/components/PreparePileup.cpp, RecFCCeeCalorimeter/src/components/CaloTowerToolFCCee.cpp
We should enable the same warnings as in Key4hep probably, but that's left for another time. Maybe it's good if some people have a look at the warnings in case the expectations were different from what the code was doing. In particular here: https://github.com/HEP-FCC/k4RecCalorimeter/pull/125/files#diff-0341e38011283eda958d6139213699c31fe2f8e76825d208ea0691a0d3529216L274-L275, where a variable was being set to itself.
=> Fix compiler warnings

RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNeighbours.cpp
Fixes a couple of issues pointed out by Archil Durglishvili when matching ecal-hcal
- bug in bin calculation (shifted by 0.5) 
- avoid looping both on ecal and hcal
Checked the impact of both changes: 1st one had tiny effect on cluster energy; 2nd has no impact as expected
=> fix for ecal-hcal barrel linking in neighbour finder

RecFCCeeCalorimeter/src/components/AugmentClustersFCCee.cpp
-  Fix NaN shape parameters by avoiding division by 0
=> avoid division by 0

RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp
- Fixes a bug introduced in #128 which broke EM-only topoclustering
=> fix topoclustering to enable EM-only clustering

RecFCCeeCalorimeter/src/components/CellPositionsECalBarrelModuleThetaSegTool.cpp, RecFCCeeCalorimeter/src/components/CellPositionsECalBarrelModuleThetaSegTool.h
The allegro ecal segmentation class has been changed to properly return a position in the volume-local coordinate system.  Remove the workaround here that was dealing with what the segmentation used to return.
- Update cell position calculation for Allegro ECal to go along with changes in k4geo.
=> Update for changes in allegro ecal segmentation.

CMakeLists.txt
- Update CMakeLists.txt to use Key4hepConfig. It had already been added to solve a problem with rpaths but some settings related to the standard from before it was added were still there.
=> Update CMakeLists.txt to use Key4hepConfig

RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNoiseLevelMap.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNoiseLevelMap.h
- The CreateFCCeeCaloNoiseLevelMap tool is updated to create noise map for phi-theta and phi-row HCal segmentations
=> Create noise map for new HCal segmentations

RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h, RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03_digi_reco.py
The cache was found by @kjvbrt to give negligible performance improvements in the past and can be problematic in MT environment and is giving errors in CI tests such as https://github.com/HEP-FCC/FCC-config/actions/runs/13949011272/job/39043242625?pr=246 so I am getting rid of it
- Remove cache of minimum noise offset and RMS for ecal in topoclustering code
- 
=> remove cache from topoclustering code

RecCalorimeter/src/components/CaloTopoCluster.cpp, RecCalorimeter/src/components/CaloTopoCluster.h, RecCalorimeter/src/components/TopoCaloNoisyCells.cpp, RecCalorimeter/src/components/TopoCaloNoisyCells.h, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h
INoiseConstTool and ICaloReadCellNoiseMap interfaces in k4FWCore provide identical functionality.
After this PR is merged we can remove the latter.
I have checked the ICaloReadCellNoiseMap is used only in those few places: https://github.com/search?q=ICaloReadCellNoiseMap&type=code
I have run the reconstruction before and after these changes and the topocluster distributions are identical
Needed by https://github.com/key4hep/k4FWCore/pull/299
- use INoiseConstTool instead of ICaloReadCellNoiseMap so that we can remove ICaloReadCellNoiseMap interface from k4FWCore (they were both providing the same functionality)
=> use INoiseConstTool instead of ICaloReadCellNoiseMap

RecCalorimeter/src/components/ConstNoiseTool.cpp, RecCalorimeter/src/components/ConstNoiseTool.h, RecFCCeeCalorimeter/CMakeLists.txt, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h, RecFCCeeCalorimeter/tests/options/IDEA_o1_v03_reco.py
- Allow topoclustering algorithm to use overrided Segmentation::neighbour function
This PR allows to use of overrided `Segmentation::neighbour` function to avoid using `TTree` based neighbor map (and instead retrieves the neighboring `CellID` on-the-fly). A switch `useNeighborMap` is added to support backward compatibility.
=> Allow topoclustering algorithm to use overrided Segmentation::neighbour function

RecCalorimeter/src/components/CalibrateBenchmarkMethod.cpp, RecCalorimeter/src/components/CalibrateBenchmarkMethod.h
- Replace Double_t with double to fix the nightlies
For some reason building these files has stopped working:
```
>> 213    /tmp/root/spack-stage/spack-stage-k4reccalorimeter-e60d5bbe08edc020
8abef9d87792615e2ee6ed4c_develop-2gwso5ans7ims5bhprmwgafc2xbrc25q/s
pack-src/RecCalorimeter/src/components/CalibrateBenchmarkMethod.h:6
7:35: error: 'Double_t' does not name a type; did you mean 'double_
t'?
214       67 |   double chiSquareFitBarrel(const Double_t* par) const;
215          |                                   ^~~~~~~~
216          |                                   double_t
```
and the fix is to simply use `double` instead of `Double_t`. Only https://github.com/HEP-FCC/k4RecCalorimeter/pull/154 was merged yesterday but I don't see the relation to …
=> Replace Double_t with double to fix the nightlies

RecCalorimeter/src/components/CreateHitTruthLinks.cpp, RecCalorimeter/src/components/CreateHitTruthLinks.h, RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03.sh, RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03_digi_reco.py
- Introduce a new Gaudi algorithm that can create a link collection between multiple input CalorimeterHit collections and MCParticles
Note: similar to what is done in Marlin in https://github.com/iLCSoft/MarlinReco/blob/master/Analysis/RecoMCTruthLink/src/RecoMCTruthLinker.cc
CLD reco uses a wrapper of that tool to save various links to truth in their output
For mlpf for ALLEGRO we need the calohit<->mcparticle links
=> Add algorithm to create links between calo hits and mc particles

RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03.sh
Using return outside of a function in a non-sourced shell script gives an error (with bash anyway):
```
return: can only `return' from a function or sourced script
```
Use exit rather than return to exit the script.
- Small fix to test script.
=> Fix bad use of return in shell script.

RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03_digi_reco.py
- Reduce the output size when running ALLEGRO_o1_v03_digi_reco
The output of this test is currently 261 MB, which makes it hard to display if it fails on CI. After this change it is 6.7 MB.
=> Reduce the output size when running ALLEGRO_o1_v03_digi_reco
