HEP-FCC/k4RecCalorimeter

RecCalorimeter/src/components/CreateCaloCells.cpp, RecCalorimeter/src/components/CreateCaloCells.h
Hello,
this PR changes EDM of CreateCaloCells tool to EDM4HEP.
best,
Juraj
=> CreateCaloCells transformed to use edm4hep

RecCalorimeter/src/components/CaloTowerTool.cpp, RecCalorimeter/src/components/CaloTowerTool.h, RecCalorimeter/src/components/CreateCaloClustersSlidingWindow.cpp, RecCalorimeter/src/components/CreateCaloClustersSlidingWindow.h, RecCalorimeter/src/components/CreateEmptyCaloCellsCollection.cpp, RecCalorimeter/src/components/CreateEmptyCaloCellsCollection.h, RecCalorimeter/src/components/LayeredCaloTowerTool.cpp, RecCalorimeter/src/components/LayeredCaloTowerTool.h, RecCalorimeter/tests/options/runFullCaloSystem_CorrectECalBarrelSliWinClusters.py, RecCalorimeter/tests/options/runFullCaloSystem_ReconstructionSW_noNoise.py, RecCalorimeter/tests/options/runFullCaloSystem_ReconstructionSW_noiseFromFile.py, RecCalorimeter/tests/options/runFullCaloSystem_ReconstructionSW_noiseFromFile_resegHCal.py
Hello,
This request adds ability to add cluster cells the same way as #426 in FCCSW.
Needs change of ITowerTool interface in k4FWCore.
Best,
Juraj
=> Adding cluster cells the same way as #426 in FCCSW

RecCalorimeter/src/components/ConeSelection.cpp, RecCalorimeter/src/components/ConeSelection.h, RecCalorimeter/src/components/CorrectECalBarrelSliWinCluster.cpp, RecCalorimeter/src/components/CorrectECalBarrelSliWinCluster.h, RecCalorimeter/src/components/CreateCaloClusters.cpp, RecCalorimeter/src/components/CreateCaloClusters.h, RecCalorimeter/src/components/MassInv.cpp, RecCalorimeter/src/components/MassInv.h, RecCalorimeter/src/components/PreparePileup.cpp, RecCalorimeter/src/components/PreparePileup.h, RecCalorimeter/src/components/SplitClusters.cpp, RecCalorimeter/src/components/SplitClusters.h
Hello :)
this request converts all remaining algorithms to use EDM4HEP:
* ConeSelection
* CorrectECalBarrelSliWinCluster
* CreateCaloClusters
* MassInv
* PreparePileup
* SplitClusters
Best,
Juraj
=> Converting all remaining algorithms to EDM4HEP

RecCalorimeter/src/components/CorrectCaloClusters.cpp, RecCalorimeter/src/components/CorrectCaloClusters.h
Hello all,
this PR adds algorithm, which corrects for the dead material and downstream leakage
Best,
Juraj
=> Adding algorithm for cluster corrections

.github/workflows/nightlies.yaml, RecCalorimeter/src/components/ReadNoiseFromFileTool.cpp, RecCalorimeter/src/components/ReadNoiseFromFileTool.h, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h, RecFCChhCalorimeter/CMakeLists.txt, RecFCChhCalorimeter/src/components/CreateFCChhCaloNoiseLevelMap.cpp, RecFCChhCalorimeter/src/components/CreateFCChhCaloNoiseLevelMap.h
Used [here](https://github.com/HEP-FCC/k4RecCalorimeter/blob/main/RecFCChhCalorimeter/src/components/CreateFCChhCaloNoiseLevelMap.cpp#L75) and [here](https://github.com/HEP-FCC/k4RecCalorimeter/blob/main/RecFCChhCalorimeter/src/components/CreateFCChhCaloNeighbours.cpp#L105)
=> Revive Topo Clustering and adapt it to FCCee

RecFCCeeCalorimeter/tests/options/runCaloSim.py
=> Add dead material correction to the test config

RecFCChhCalorimeter/src/components/CellPositionsHCalBarrelTool.h, RecFCChhCalorimeter/src/components/CreateFCChhCaloNeighbours.cpp
Update in order to be compatible with new HCal geometry https://github.com/HEP-FCC/FCCDetectors/pull/27 . Tagging @faltovaj and @BrieucF to keep them in the loop.
=> update cell positions based on new geometry

RecFCCeeCalorimeter/tests/options/runCaloSim.py
Updates required by PR #28 in FCCDetectors (https://github.com/HEP-FCC/FCCDetectors/pull/28)
- Addition of Ecal endcaps reconstruction in the main script
- Updating Ecal barrel calibration constants
=> Update of run example

RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.h
@BrieucF @faltovaj changed DetID_HCAL_Barrel from 10 to 8 following the changes in FCCDetectors https://github.com/HEP-FCC/FCCDetectors/pull/28/files#diff-7c664375e73ed204eaacb20785ab3e674cf8c682614cd04b9bf00b4fb9413895
=> Update systemID following new geometry

RecFCCeeCalorimeter/tests/options/fcc_ee_caloBenchmarkCalibration.py, RecFCCeeCalorimeter/tests/options/runFullCaloSystem_ReconstructionSW_noiseFromFile.py
Fixes typos from https://github.com/HEP-FCC/k4RecCalorimeter/pull/45.
=> fix creation of the list of detectors

RecCalorimeter/src/components/CalibrateBenchmarkMethod.cpp, RecCalorimeter/src/components/CaloTopoCluster.cpp, RecCalorimeter/src/components/CorrectCaloClusters.cpp, RecCalorimeter/src/components/CorrectCaloClusters.h, RecCalorimeter/src/components/CorrectECalBarrelSliWinCluster.cpp, RecCalorimeter/src/components/MassInv.cpp, RecCalorimeter/src/components/NoiseCaloCellsFlatTool.cpp, RecCalorimeter/src/components/PreparePileup.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNeighbours.cpp
One more remaining because of `ITowerTool`.
One warning remaining. The `LayeredCaloTowerTool` does not save cells of the towers.
=> Attempt to fix warnings :)

RecFCCeeCalorimeter/tests/options/runCaloSim.py
Fix related to:  https://github.com/HEP-FCC/FCCSW/issues/361
"+=" will not work on uninitialized array.
=> Creating empty array for SimG4Alg.outputs

CMakeLists.txt, RecCalorimeter/src/components/CreateCaloCells.h, RecFCCeeCalorimeter/src/components/CreateCaloCellPositionsFCCee.h
Supersedes https://github.com/HEP-FCC/k4RecCalorimeter/pull/54 (sorry, I can't push to that branch since I'm not a maintainer in HEP-FCC). Should build with the nightlies tomorrow.
=> Use the new edm4hep::CellIDEncoding

RecCalorimeter/src/components/CreateCaloClustersSlidingWindow.h
Otherwise it pollutes global namespace.
=> Hiding cluster sctruct definition in algoritm

RecFCCeeCalorimeter/src/components/CaloTowerToolFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTowerToolFCCee.h
Added the possibility to run sliding window algorithm on HCal and ECal+HCal. 
Tagging @BrieucF , @giovannimarchiori and @dasphy
=> update SW to run on HCal

RecCaloCommon/include/RecCaloCommon/ClusterJet.h, RecCaloCommon/src/ClusterJet.cpp, RecCalorimeter/src/components/CreateCaloJet.cpp, RecCalorimeter/src/components/CreateTruthJet.cpp
Small adjustments of edge cases.
=> Adjusting JetCluster class

CMakeLists.txt
Too many false positives
See discussion in #115
=> Disable dangling-reference warning

RecCalorimeter/src/components/CorrectECalBarrelSliWinCluster.cpp, RecCalorimeter/src/components/CorrectECalBarrelSliWinCluster.h, RecCalorimeter/src/components/CreateCaloClusters.cpp, RecCalorimeter/src/components/CreateCaloClusters.h, RecCalorimeter/src/components/MassInv.cpp, RecCalorimeter/src/components/MassInv.h, RecCalorimeter/src/components/NoiseCaloCellsFlatTool.cpp, RecCalorimeter/src/components/NoiseCaloCellsFlatTool.h, RecCalorimeter/src/components/NoiseCaloCellsFromFileTool.cpp, RecCalorimeter/src/components/NoiseCaloCellsFromFileTool.h, RecFCCeeCalorimeter/src/components/NoiseCaloCellsVsThetaFromFileTool.cpp, RecFCCeeCalorimeter/src/components/NoiseCaloCellsVsThetaFromFileTool.h
see https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1637
- Fix service retrieval after deprecations in Gaudi v39r1, see https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1637
Like in https://github.com/key4hep/k4FWCore/pull/256
=> Fix service retrieval after deprecations in Gaudi v39r1

RecCalorimeter/tests/options/runEcalBarrel_ReconstructionTopoClusters_crosstalk.py
- Update the path to the reference SIM file for cross-talk ctests
=> Update path to the reference SIM file for cross-talk tests

RecCalorimeter/src/components/CreatePositionedCaloCells.cpp, RecCalorimeter/src/components/CreatePositionedCaloCells.h, RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03_digi_reco.py
- Add code to create and persist digi<->hit links in CreatePositionedCaloCells
=> add calo digi<->hit links to calo digitiser

RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNoiseLevelMap.cpp, RecFCCeeCalorimeter/src/components/CreateFCCeeCaloNoiseLevelMap.h
- Retrieve ecal endcap positioning tool in topocluster algorithm 
=> retrieve ecal endcap positioning tool

RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.cpp, RecFCCeeCalorimeter/src/components/CaloTopoClusterFCCee.h, RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03.sh, RecFCCeeCalorimeter/tests/options/ALLEGRO_o1_v03_digi_reco.py
- exploit the fact that cells are already positioned to avoid using positioning tools in topoclustering code. 
Cells are already positioned (either using CreateCaloCells with addPositions or CreatePositionedCaloCells) so topoclustering does not need to retrieve again cell positions, and can be significantly simplified. 
The code is basically a port of #57 migrating GaudiAlgorithm to Gaudi::Algorithm and creating on the fly in the execute() method the collection of all cells merging together the list of input cell collections. 
I ran the code with old and new version of the algorithm finding very good agreement.
Usage example:
old alg:
```
topoClusterInputTool = CaloTopoClusterInputTool(outputClusters + "InputTool", …
```
=> Topoclustering using already positioned cells

CMakeLists.txt
- Add LANGUAGES CXX to disable checks for a C compiler
=> Add LANGUAGES CXX to disable checks for a C compiler
